// <auto-generated />
using MVC_EFCF.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MVC_EFCF.Migrations
{
    [DbContext(typeof(MVC_EFCFContext))]
    [Migration("20220203011547_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("MVC_EFCF.Models.Detail", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("IdTaxDocument")
                        .HasColumnType("bigint");

                    b.Property<decimal>("PartialAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("SingleAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<long>("taxDocumentId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("taxDocumentId");

                    b.ToTable("Detail");
                });

            modelBuilder.Entity("MVC_EFCF.Models.TaxDocument", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<short>("Currency")
                        .HasColumnType("smallint");

                    b.Property<string>("DocumentComplement")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("DocumentNumber")
                        .HasColumnType("bigint");

                    b.Property<short>("DocumentType")
                        .HasColumnType("smallint");

                    b.Property<long>("NIT")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("TaxDocument");
                });

            modelBuilder.Entity("MVC_EFCF.Models.Detail", b =>
                {
                    b.HasOne("MVC_EFCF.Models.TaxDocument", "taxDocument")
                        .WithMany("Detail")
                        .HasForeignKey("taxDocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("taxDocument");
                });

            modelBuilder.Entity("MVC_EFCF.Models.TaxDocument", b =>
                {
                    b.Navigation("Detail");
                });
#pragma warning restore 612, 618
        }
    }
}
